services:
  api:
    build:
      context: ../../
    ports:
      - "3001:3001"
    environment: # te rog Adrian sa pui totul asta in ../config/.env.dev
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskmanager;Username=taskmanager;Password=taskmanager_dev
      - Jwt__Key=TaskManagerSuperSecretKey_ChangeInProduction_AtLeast32Chars!
      - Jwt__Issuer=TaskManager.API
      - Jwt__Audience=TaskManager.Client
      - Jwt__ExpirationInMinutes=60
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Exchange=task-events
    networks:
      - taskflow-net
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_PASSWORD: taskmanager_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - taskflow-net

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  taskflow-net:
    external: true